# ====================== r1 车相对雷达 ======================
_r1_xyzrpy_car_xyz_x_: -0.40944
_r1_xyzrpy_car_xyz_y_: 0.45344        # 0.40944 + 0.088/2
_r1_xyzrpy_car_xyz_z_: 0.0
_r1_xyzrpy_car_rpy_roll_: 0.0
_r1_xyzrpy_car_rpy_pitch_: 0.0
_r1_xyzrpy_car_rpy_yaw_: -1.57079632679   # -PI/2

# ====================== r1 建图误差 ======================
_r1_xyzrpy_error_xyz_x_: 0.025
_r1_xyzrpy_error_xyz_y_: -0.045
_r1_xyzrpy_error_xyz_z_: 0.10
_r1_xyzrpy_error_rpy_roll_: 0.0
_r1_xyzrpy_error_rpy_pitch_: 0.0
_r1_xyzrpy_error_rpy_yaw_: 0.0

# ====================== r2 车相对雷达 ======================
_r2_xyzrpy_car_xyz_x_: 0.0
_r2_xyzrpy_car_xyz_y_: 0.28
_r2_xyzrpy_car_xyz_z_: 0.0
_r2_xyzrpy_car_rpy_roll_: 0.0
_r2_xyzrpy_car_rpy_pitch_: 0.0
_r2_xyzrpy_car_rpy_yaw_: 0.0

# ====================== r2 建图误差 ======================
_r2_xyzrpy_error_xyz_x_: 0.025
_r2_xyzrpy_error_xyz_y_: -0.045
_r2_xyzrpy_error_xyz_z_: 0.10
_r2_xyzrpy_error_rpy_roll_: 0.0
_r2_xyzrpy_error_rpy_pitch_: 0.0
_r2_xyzrpy_error_rpy_yaw_: 0.0

# ====================== 识别路径 / 检测 ======================
_coner_path_: "/home/robocon/rc2026/model/corner5/best"
_juanzhou_path_: "/home/robocon/rc2026/model/juanZhou_cls1/best"
_box_num_: 5

# ====================== 串口 ======================
_max_serial_num_: 10

# ====================== 重定位参数 ======================
_voxeldownsample_threshold_for_teaser_: 0.3
_voxeldownsample_threshold_for_icp_: 0.5
_setmaxcorrespondencedistance_nano_gicp_: 0.55
_min_num_of_point_cloud_for_relocation_: 20000

#=============建图下采样参数===================
_voxeldownsample_threshold_: 0.3

# ====================== 相机内参（新加 8 个） ======================
# 640x480
camera_fx_640: 553.7294
camera_fy_640: 553.7891
camera_cx_640: 317.2345
camera_cy_640: 239.7654

# 1920x1080
camera_fx_1080: 1384.4351
camera_fy_1080: 1385.0789
camera_cx_1080: 960.1845
camera_cy_1080: 540.2312
